services:
  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=converter
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  # api:
  #   build: converter-api
  #   volumes:
  #     - video-volume:/video
  #   environment:
  #     - BROKER=redis://redis:6379/0
  #     - DATABASE_URL=postgresql://postgres:postgres@db/converter
  #     - VIDEO_DIR=/video
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #     db:
  #       condition: service_healthy
  worker:
    build: converter-worker
    volumes:
      - video-volume:/video
    environment:
      - BROKER=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:postgres@db/converter
      - VIDEO_DIR=/video
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  # nginx:
  #   build: nginx
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - api
  trigger:
    build: trigger
    environment:
      - BROKER=redis://redis:6379/0
      - NUM_PARALLEL_TASKS=5
      - NUM_CYCLES=1
      - VIDEO_DIR=/video
      - OLD_FORMAT=mp4
      - NEW_FORMAT=webm
      - DEMO_VIDEO=demo.mp4
      - DATABASE_URL=postgresql://postgres:postgres@db/converter
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    volumes:
      - video-volume:/video
volumes:
  video-volume:
