services:
  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=converter
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build: converter-api
    environment:
      - BROKER=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:postgres@db/converter
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  worker:
    build: converter-worker
    environment:
      - BROKER=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:postgres@db/converter
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
